### PR TITLE
Add support to React 17

### PR DESCRIPTION
**Pull request by guilhermemj**
Hello there! Just wanted to update some dependencies in order to use this library with React 17 (might as well do a similar PR for React 18 in the future).

The biggest changes are using `@wojtekmaj/enzyme-adapter-react-17` in favor of `enzyme-adapter-react-16` as there seems to be no official enzyme adapter for React 17 and that the package-lock.json was generated using npm v7 (all should be transparent to users).

### CODE REVIEW

**Comment by hswolff** [comment]
Thanks for the PR!

Is the issue the peerDependencies? I wonder if we can broaden the peerDeps and leave the code alone as we're not really using any newer React features.

```
  "peerDependencies": {
    "react": "^16.6.0-0 || ^17.0.0 || ^18.0.0"
  },
```

**Comment by guilhermemj** [comment]
Actually that would work too! Should I create another PR with your proposed changes or the maintainers will do it?

**Comment by hswolff** [comment]
I'll take care of it, plus push out a new version with that. Ty for the nudge!

**Comment by hswolff** [comment]
Done! https://github.com/mongodb-js/connect-backbone-to-react/commit/59562bbd6cd856834100c728de55ac5b1f688bc4

**Comment by guilhermemj** [comment]
Thank you very much!

**Pull request closed without merging**
